/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.un.ldcportal.ismapplications.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.portlet.asset.service.AssetEntryLocalService;
import com.liferay.portlet.asset.service.AssetEntryService;
import com.liferay.portlet.asset.service.persistence.AssetEntryPersistence;

import org.un.ldcportal.ismapplications.model.ISMApplication;
import org.un.ldcportal.ismapplications.service.ISMApplicationLocalService;
import org.un.ldcportal.ismapplications.service.ISMLocalService;
import org.un.ldcportal.ismapplications.service.persistence.ISMApplicationPersistence;
import org.un.ldcportal.ismapplications.service.persistence.ISMPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the i s m application local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.un.ldcportal.ismapplications.service.impl.ISMApplicationLocalServiceImpl}.
 * </p>
 *
 * @author Thibault Boyeux
 * @see org.un.ldcportal.ismapplications.service.impl.ISMApplicationLocalServiceImpl
 * @see org.un.ldcportal.ismapplications.service.ISMApplicationLocalServiceUtil
 * @generated
 */
public abstract class ISMApplicationLocalServiceBaseImpl
	implements ISMApplicationLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.un.ldcportal.ismapplications.service.ISMApplicationLocalServiceUtil} to access the i s m application local service.
	 */

	/**
	 * Adds the i s m application to the database. Also notifies the appropriate model listeners.
	 *
	 * @param ismApplication the i s m application
	 * @return the i s m application that was added
	 * @throws SystemException if a system exception occurred
	 */
	public ISMApplication addISMApplication(ISMApplication ismApplication)
		throws SystemException {
		ismApplication.setNew(true);

		ismApplication = ismApplicationPersistence.update(ismApplication, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(ismApplication);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return ismApplication;
	}

	/**
	 * Creates a new i s m application with the primary key. Does not add the i s m application to the database.
	 *
	 * @param ismApplicationId the primary key for the new i s m application
	 * @return the new i s m application
	 */
	public ISMApplication createISMApplication(long ismApplicationId) {
		return ismApplicationPersistence.create(ismApplicationId);
	}

	/**
	 * Deletes the i s m application with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param ismApplicationId the primary key of the i s m application
	 * @throws PortalException if a i s m application with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteISMApplication(long ismApplicationId)
		throws PortalException, SystemException {
		ISMApplication ismApplication = ismApplicationPersistence.remove(ismApplicationId);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(ismApplication);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the i s m application from the database. Also notifies the appropriate model listeners.
	 *
	 * @param ismApplication the i s m application
	 * @throws PortalException
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteISMApplication(ISMApplication ismApplication)
		throws PortalException, SystemException {
		ismApplicationPersistence.remove(ismApplication);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(ismApplication);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return ismApplicationPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return ismApplicationPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return ismApplicationPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return ismApplicationPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public ISMApplication fetchISMApplication(long ismApplicationId)
		throws SystemException {
		return ismApplicationPersistence.fetchByPrimaryKey(ismApplicationId);
	}

	/**
	 * Returns the i s m application with the primary key.
	 *
	 * @param ismApplicationId the primary key of the i s m application
	 * @return the i s m application
	 * @throws PortalException if a i s m application with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public ISMApplication getISMApplication(long ismApplicationId)
		throws PortalException, SystemException {
		return ismApplicationPersistence.findByPrimaryKey(ismApplicationId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return ismApplicationPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the i s m application with the UUID in the group.
	 *
	 * @param uuid the UUID of i s m application
	 * @param groupId the group id of the i s m application
	 * @return the i s m application
	 * @throws PortalException if a i s m application with the UUID in the group could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public ISMApplication getISMApplicationByUuidAndGroupId(String uuid,
		long groupId) throws PortalException, SystemException {
		return ismApplicationPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the i s m applications.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of i s m applications
	 * @param end the upper bound of the range of i s m applications (not inclusive)
	 * @return the range of i s m applications
	 * @throws SystemException if a system exception occurred
	 */
	public List<ISMApplication> getISMApplications(int start, int end)
		throws SystemException {
		return ismApplicationPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of i s m applications.
	 *
	 * @return the number of i s m applications
	 * @throws SystemException if a system exception occurred
	 */
	public int getISMApplicationsCount() throws SystemException {
		return ismApplicationPersistence.countAll();
	}

	/**
	 * Updates the i s m application in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param ismApplication the i s m application
	 * @return the i s m application that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ISMApplication updateISMApplication(ISMApplication ismApplication)
		throws SystemException {
		return updateISMApplication(ismApplication, true);
	}

	/**
	 * Updates the i s m application in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param ismApplication the i s m application
	 * @param merge whether to merge the i s m application with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the i s m application that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ISMApplication updateISMApplication(ISMApplication ismApplication,
		boolean merge) throws SystemException {
		ismApplication.setNew(false);

		ismApplication = ismApplicationPersistence.update(ismApplication, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(ismApplication);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return ismApplication;
	}

	/**
	 * Returns the i s m local service.
	 *
	 * @return the i s m local service
	 */
	public ISMLocalService getISMLocalService() {
		return ismLocalService;
	}

	/**
	 * Sets the i s m local service.
	 *
	 * @param ismLocalService the i s m local service
	 */
	public void setISMLocalService(ISMLocalService ismLocalService) {
		this.ismLocalService = ismLocalService;
	}

	/**
	 * Returns the i s m persistence.
	 *
	 * @return the i s m persistence
	 */
	public ISMPersistence getISMPersistence() {
		return ismPersistence;
	}

	/**
	 * Sets the i s m persistence.
	 *
	 * @param ismPersistence the i s m persistence
	 */
	public void setISMPersistence(ISMPersistence ismPersistence) {
		this.ismPersistence = ismPersistence;
	}

	/**
	 * Returns the i s m application local service.
	 *
	 * @return the i s m application local service
	 */
	public ISMApplicationLocalService getISMApplicationLocalService() {
		return ismApplicationLocalService;
	}

	/**
	 * Sets the i s m application local service.
	 *
	 * @param ismApplicationLocalService the i s m application local service
	 */
	public void setISMApplicationLocalService(
		ISMApplicationLocalService ismApplicationLocalService) {
		this.ismApplicationLocalService = ismApplicationLocalService;
	}

	/**
	 * Returns the i s m application persistence.
	 *
	 * @return the i s m application persistence
	 */
	public ISMApplicationPersistence getISMApplicationPersistence() {
		return ismApplicationPersistence;
	}

	/**
	 * Sets the i s m application persistence.
	 *
	 * @param ismApplicationPersistence the i s m application persistence
	 */
	public void setISMApplicationPersistence(
		ISMApplicationPersistence ismApplicationPersistence) {
		this.ismApplicationPersistence = ismApplicationPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the asset entry local service.
	 *
	 * @return the asset entry local service
	 */
	public AssetEntryLocalService getAssetEntryLocalService() {
		return assetEntryLocalService;
	}

	/**
	 * Sets the asset entry local service.
	 *
	 * @param assetEntryLocalService the asset entry local service
	 */
	public void setAssetEntryLocalService(
		AssetEntryLocalService assetEntryLocalService) {
		this.assetEntryLocalService = assetEntryLocalService;
	}

	/**
	 * Returns the asset entry remote service.
	 *
	 * @return the asset entry remote service
	 */
	public AssetEntryService getAssetEntryService() {
		return assetEntryService;
	}

	/**
	 * Sets the asset entry remote service.
	 *
	 * @param assetEntryService the asset entry remote service
	 */
	public void setAssetEntryService(AssetEntryService assetEntryService) {
		this.assetEntryService = assetEntryService;
	}

	/**
	 * Returns the asset entry persistence.
	 *
	 * @return the asset entry persistence
	 */
	public AssetEntryPersistence getAssetEntryPersistence() {
		return assetEntryPersistence;
	}

	/**
	 * Sets the asset entry persistence.
	 *
	 * @param assetEntryPersistence the asset entry persistence
	 */
	public void setAssetEntryPersistence(
		AssetEntryPersistence assetEntryPersistence) {
		this.assetEntryPersistence = assetEntryPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("org.un.ldcportal.ismapplications.model.ISMApplication",
			ismApplicationLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"org.un.ldcportal.ismapplications.model.ISMApplication");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return ISMApplication.class;
	}

	protected String getModelClassName() {
		return ISMApplication.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = ismApplicationPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ISMLocalService.class)
	protected ISMLocalService ismLocalService;
	@BeanReference(type = ISMPersistence.class)
	protected ISMPersistence ismPersistence;
	@BeanReference(type = ISMApplicationLocalService.class)
	protected ISMApplicationLocalService ismApplicationLocalService;
	@BeanReference(type = ISMApplicationPersistence.class)
	protected ISMApplicationPersistence ismApplicationPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@BeanReference(type = AssetEntryLocalService.class)
	protected AssetEntryLocalService assetEntryLocalService;
	@BeanReference(type = AssetEntryService.class)
	protected AssetEntryService assetEntryService;
	@BeanReference(type = AssetEntryPersistence.class)
	protected AssetEntryPersistence assetEntryPersistence;
	private static Log _log = LogFactoryUtil.getLog(ISMApplicationLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}