/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.un.ldcportal.jargon.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import org.un.ldcportal.jargon.model.LDCJargon;
import org.un.ldcportal.jargon.service.LDCJargonLocalService;
import org.un.ldcportal.jargon.service.persistence.LDCJargonPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the l d c jargon local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.un.ldcportal.jargon.service.impl.LDCJargonLocalServiceImpl}.
 * </p>
 *
 * @author Thibault Boyeux
 * @see org.un.ldcportal.jargon.service.impl.LDCJargonLocalServiceImpl
 * @see org.un.ldcportal.jargon.service.LDCJargonLocalServiceUtil
 * @generated
 */
public abstract class LDCJargonLocalServiceBaseImpl
	implements LDCJargonLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.un.ldcportal.jargon.service.LDCJargonLocalServiceUtil} to access the l d c jargon local service.
	 */

	/**
	 * Adds the l d c jargon to the database. Also notifies the appropriate model listeners.
	 *
	 * @param ldcJargon the l d c jargon
	 * @return the l d c jargon that was added
	 * @throws SystemException if a system exception occurred
	 */
	public LDCJargon addLDCJargon(LDCJargon ldcJargon)
		throws SystemException {
		ldcJargon.setNew(true);

		ldcJargon = ldcJargonPersistence.update(ldcJargon, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(ldcJargon);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return ldcJargon;
	}

	/**
	 * Creates a new l d c jargon with the primary key. Does not add the l d c jargon to the database.
	 *
	 * @param ldcJargonId the primary key for the new l d c jargon
	 * @return the new l d c jargon
	 */
	public LDCJargon createLDCJargon(long ldcJargonId) {
		return ldcJargonPersistence.create(ldcJargonId);
	}

	/**
	 * Deletes the l d c jargon with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param ldcJargonId the primary key of the l d c jargon
	 * @throws PortalException if a l d c jargon with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteLDCJargon(long ldcJargonId)
		throws PortalException, SystemException {
		LDCJargon ldcJargon = ldcJargonPersistence.remove(ldcJargonId);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(ldcJargon);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the l d c jargon from the database. Also notifies the appropriate model listeners.
	 *
	 * @param ldcJargon the l d c jargon
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteLDCJargon(LDCJargon ldcJargon) throws SystemException {
		ldcJargonPersistence.remove(ldcJargon);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(ldcJargon);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return ldcJargonPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return ldcJargonPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return ldcJargonPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return ldcJargonPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public LDCJargon fetchLDCJargon(long ldcJargonId) throws SystemException {
		return ldcJargonPersistence.fetchByPrimaryKey(ldcJargonId);
	}

	/**
	 * Returns the l d c jargon with the primary key.
	 *
	 * @param ldcJargonId the primary key of the l d c jargon
	 * @return the l d c jargon
	 * @throws PortalException if a l d c jargon with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public LDCJargon getLDCJargon(long ldcJargonId)
		throws PortalException, SystemException {
		return ldcJargonPersistence.findByPrimaryKey(ldcJargonId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return ldcJargonPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the l d c jargons.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of l d c jargons
	 * @param end the upper bound of the range of l d c jargons (not inclusive)
	 * @return the range of l d c jargons
	 * @throws SystemException if a system exception occurred
	 */
	public List<LDCJargon> getLDCJargons(int start, int end)
		throws SystemException {
		return ldcJargonPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of l d c jargons.
	 *
	 * @return the number of l d c jargons
	 * @throws SystemException if a system exception occurred
	 */
	public int getLDCJargonsCount() throws SystemException {
		return ldcJargonPersistence.countAll();
	}

	/**
	 * Updates the l d c jargon in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param ldcJargon the l d c jargon
	 * @return the l d c jargon that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public LDCJargon updateLDCJargon(LDCJargon ldcJargon)
		throws SystemException {
		return updateLDCJargon(ldcJargon, true);
	}

	/**
	 * Updates the l d c jargon in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param ldcJargon the l d c jargon
	 * @param merge whether to merge the l d c jargon with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the l d c jargon that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public LDCJargon updateLDCJargon(LDCJargon ldcJargon, boolean merge)
		throws SystemException {
		ldcJargon.setNew(false);

		ldcJargon = ldcJargonPersistence.update(ldcJargon, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(ldcJargon);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return ldcJargon;
	}

	/**
	 * Returns the l d c jargon local service.
	 *
	 * @return the l d c jargon local service
	 */
	public LDCJargonLocalService getLDCJargonLocalService() {
		return ldcJargonLocalService;
	}

	/**
	 * Sets the l d c jargon local service.
	 *
	 * @param ldcJargonLocalService the l d c jargon local service
	 */
	public void setLDCJargonLocalService(
		LDCJargonLocalService ldcJargonLocalService) {
		this.ldcJargonLocalService = ldcJargonLocalService;
	}

	/**
	 * Returns the l d c jargon persistence.
	 *
	 * @return the l d c jargon persistence
	 */
	public LDCJargonPersistence getLDCJargonPersistence() {
		return ldcJargonPersistence;
	}

	/**
	 * Sets the l d c jargon persistence.
	 *
	 * @param ldcJargonPersistence the l d c jargon persistence
	 */
	public void setLDCJargonPersistence(
		LDCJargonPersistence ldcJargonPersistence) {
		this.ldcJargonPersistence = ldcJargonPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("org.un.ldcportal.jargon.model.LDCJargon",
			ldcJargonLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"org.un.ldcportal.jargon.model.LDCJargon");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return LDCJargon.class;
	}

	protected String getModelClassName() {
		return LDCJargon.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = ldcJargonPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = LDCJargonLocalService.class)
	protected LDCJargonLocalService ldcJargonLocalService;
	@BeanReference(type = LDCJargonPersistence.class)
	protected LDCJargonPersistence ldcJargonPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(LDCJargonLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}