/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.un.ldcportal.jargon.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LDCJargon service. Represents a row in the &quot;LDCJargon_LDCJargon&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.un.ldcportal.jargon.model.impl.LDCJargonModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.un.ldcportal.jargon.model.impl.LDCJargonImpl}.
 * </p>
 *
 * @author Thibault Boyeux
 * @see LDCJargon
 * @see org.un.ldcportal.jargon.model.impl.LDCJargonImpl
 * @see org.un.ldcportal.jargon.model.impl.LDCJargonModelImpl
 * @generated
 */
public interface LDCJargonModel extends BaseModel<LDCJargon> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l d c jargon model instance should use the {@link LDCJargon} interface instead.
	 */

	/**
	 * Returns the primary key of this l d c jargon.
	 *
	 * @return the primary key of this l d c jargon
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l d c jargon.
	 *
	 * @param primaryKey the primary key of this l d c jargon
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ldc jargon ID of this l d c jargon.
	 *
	 * @return the ldc jargon ID of this l d c jargon
	 */
	public long getLdcJargonId();

	/**
	 * Sets the ldc jargon ID of this l d c jargon.
	 *
	 * @param ldcJargonId the ldc jargon ID of this l d c jargon
	 */
	public void setLdcJargonId(long ldcJargonId);

	/**
	 * Returns the name of this l d c jargon.
	 *
	 * @return the name of this l d c jargon
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this l d c jargon.
	 *
	 * @param name the name of this l d c jargon
	 */
	public void setName(String name);

	/**
	 * Returns the definition of this l d c jargon.
	 *
	 * @return the definition of this l d c jargon
	 */
	@AutoEscape
	public String getDefinition();

	/**
	 * Sets the definition of this l d c jargon.
	 *
	 * @param definition the definition of this l d c jargon
	 */
	public void setDefinition(String definition);

	/**
	 * Returns the company ID of this l d c jargon.
	 *
	 * @return the company ID of this l d c jargon
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this l d c jargon.
	 *
	 * @param companyId the company ID of this l d c jargon
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this l d c jargon.
	 *
	 * @return the group ID of this l d c jargon
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this l d c jargon.
	 *
	 * @param groupId the group ID of this l d c jargon
	 */
	public void setGroupId(long groupId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LDCJargon ldcJargon);

	public int hashCode();

	public CacheModel<LDCJargon> toCacheModel();

	public LDCJargon toEscapedModel();

	public String toString();

	public String toXmlString();
}